services:
  gretl:
    image: sogis/gretl:${GRETL_IMAGE_TAG:-2.2.617}
    profiles: ["app"]
    environment:
      ORG_GRADLE_PROJECT_gretlEnvironment: development
    entrypoint: ["gretl", "--project-cache-dir=/home/gradle/projectcache"]
    volumes:
      - type: bind
        source: .
        target: /home/gradle/project
      - type: bind
        source: $HOME/gretljobs.properties
        target: /home/gradle/.gradle/gradle.properties
  search-db:
    image: bitnami/postgresql:14.8.0-debian-11-r74
    environment:
      POSTGRESQL_DATABASE: search
      POSTGRESQL_USERNAME: ddluser
      POSTGRESQL_PASSWORD: ddluser
      POSTGRESQL_USERNAME_2: dmluser
      POSTGRESQL_PASSWORD_2: dmluser
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_INITSCRIPTS_USERNAME: postgres
      POSTGRESQL_INITSCRIPTS_PASSWORD: secret
    ports:
      - "54326:5432"
    volumes:
      - type: bind
        source: ./docker-compose/preinitdb.d
        target: /docker-entrypoint-preinitdb.d
      - type: bind
        source: ./docker-compose/initdb.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: pgdat_search
        target: /bitnami/postgresql
volumes:
  pgdat_search:
