@startuml

[Clients] as c

note right
  Web GIS Client
  SO-Locator
  SO-Bau
  ...
end note

[Such-Service] as s

database "Suchindex-Tabellen" as stbl {
  rectangle "Geo Indextabelle" as geo
  rectangle "Meta Indextabelle" as meta
}

database "Geo-Tabellen" as gtbl {
}

database "Meta-Tabellen" as mtbl {
}

c --> s

s --> geo
s --> meta

gtbl -up-> geo : GRETL
mtbl -up-> meta : GRETL

@enduml